TodoApp/urls.py
from django.urls import path
from . import views
app_name='shop'
urlpatterns = [
    path('',views.Home,name='home'),
    path('<slug:c_slug>/',views.Home,name='product_by_category'),
    path('details/<int:id>',views.Details,name='details'),
    path('about_farmers',views.aboutfarmer,name='farmers'),
    path('about_US',views.aboutus,name='about.us')

]

Todoproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls')), 
    path('auth/',include('userarauth.urls')), 
    path('searchapp/',include('searchapp.urls')),
    path('cartapp/',include('cartapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    
    path('addcart/<int:id>',views.addcart,name='addcart'),
    path('displaycart/',views.displaycart,name='displaycart'),

]

cartapp/urls.py
from .import views
from django.urls import path
app_name='cartapp'
urlpatterns = [
    path('addcart/<int:id>',views.addcart,name='addcart'),
    path('removecart/<int:id>',views.removecart,name='removecart'),
    path('fullremove/<int:id>',views.fullremove,name='fullremove'),
    path('displaycart/',views.displaycart,name='displaycart'),
    path('placeorder/',views.placeorder,name='placeorder'),
]

searchapp/urls.py
from django.urls import path
from . import views
app_name='searchapp'
urlpatterns = [
    path('searchproduct/',views.SearchResult,name='searchproduct'),
]

userarauth/urls.py
from django.urls import path
from.import views

app_name='auth'
urlpatterns = [
    path('register/',views.registerUser,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),

    
    
]

cart/models.py
from django.db import models
from TodoApp.models import Product

# Create your models here.
class Cart(models.Model):
    user=models.CharField(max_length=200)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    
    class Meta:
        db_table='cart'
 

cart/views.py
from django.shortcuts import render,redirect
from TodoApp.models import Product
from.models import Cart
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def addcart(req,id):
    user=req.session['user']
    product=Product.objects.get(id=id)
    print(product)
    try:
        cart=Cart.objects.get(product=product)
        if cart.quantity<cart.product.stock:
            cart.quantity+=1
            cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(user=user,product=product,quantity=1)
    return redirect('cart:displaycart')

def displaycart(req):
    user=req.session['user']
    
      
    cart=Cart.objects.all().filter(user=user)
    return render(req,'cart.html',{'cart':cart})

templates/about_farmers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="farmers">


<section id="page-header" class="blog-header">
    <h2>Fresh from Farm to Your Plate</h2>
    <p>Farmer to Customer Journey in Less than a Day!!</p>


</section>
<section id="blog">
    <div class="blog-box">
        <div class="blog-img">
            <img src="{% static 'images/farmer2.jpg' %}"  alt="farmer1" ></a>
        </div>
        <div class="blog-details"></div>
        <h4>Kozhinjapara-New Farming Grounds</h4>
        <p>Kozhinjapara is a small village located in Palakkad district, Kerala. This farming village lies very close to the Kerala-Tamil Nadu border. Like Vattavada, farming is the main occupation of the people residing in Kozhinjapara. Vegetables like pumpkin, cucumber, ladyfinger, ash gourd, tomato, brinjal, spinach, gooseberry, ivy gourd are harvested on a large-scale production.</p>
        <a href="#">CONTINUE READING</a>
        <h1>13/01</h1>
    </div>
    <div class="blog-box">
        <div class="blog-img">
            <img src="{% static 'images/FAMR2.jpg' %}"  alt="farmer2" ></a>
        </div>
        <div class="blog-details"></div>
        <h4>Meet Sijo From Kerala!</h4>
        <p>“I am a South Indian, born and raised in UAE. My dad comes from a family of farmers and with little knowledge he started planting some plants like Mint, Moringa, Curry leaf, Aloe Vera, Tomato, Tapioca, Melon, Indian Spinach, Sweet potato by the side of our house. Due to the heat and not enough knowledge, the harvest used to be very low but we enjoyed working side by side. Those are the fondest memories I have with my father. We are well known in our neighbourhood because we share our beans, Moringa and tapioca with everyone who simply glances at our garden.</p>
        <a href="#">CONTINUE READING</a>
        <h1>13/01</h1>
    </div>
    <div class="blog-box">
        <div class="blog-img">
            <img src="{% static 'images/FARMR5.jpg' %}"  alt="farmer3" ></a>
        </div>
        <div class="blog-details"></div>
        <h4>Attempt to revive Traditional sustainable agricultural practices of Kerala</h4>
        <p> I am anu rajan. I was raised in Bombay and currently based in Kannur, Kerala.
            Sustainable living has been my dream since the past couple of years and in the meanwhile I have gone through various changes in my career.</p>
        <a href="#">CONTINUE READING</a>
        <h1>13/01</h1>
    </div>
    <div class="blog-box">
        <div class="blog-img">
            <img src="{% static 'images/FARMR6.jpg' %}"  alt="farmer4" ></a>
        </div>
        <div class="blog-details"></div>
        <h4>Payar (Cowpea) Farming and Caring</h4>
        <p>Cowpea can be cultivated very easly, It is easy to grow, even for beginners can do, and well in any climate. Cultivated in a wide range of soils in kerala, very well in sandy and sandy loam soils. Make sure the soil is rich in organic matter. It is widely cultivated in Kerala even in courtyard, terrace and farms.</p>
        <a href="#">CONTINUE READING</a>
        <h1>13/01</h1>
    </div>
</section>




<section id="pagination" class="section-p1">
    <a href="#">1</a>
    <a href="#">2</a>
    <a href="#"><i class="fa-solid fa-arrow-right-long"></i></a>
</section>




<section id="newsletter" class="section-p1 section-m1">
    <div class="newstext">
        <h4>Sign up for Newsletters</h4>
        <p>Get email updates about our latest <span>special offers</span></p>
    </div>
    <div class="form">
        <input type="text" placeholder="Your email address">
        <button class="normal">Sign up</button>
    </div>
</section>


<script src="{% static 'script.js' %}"></script>
</div>

{% endblock %}

templates/about_us.html
<!doctype html>

<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'static/script.js' %}"></script>


    <title>Harvest Haven</title>
</head>
<body>
<section id="header">
    <a href="#"><img src="{% static 'images/logo.jpg' %}" class="logo" alt="image1" ></a>
    <div>
        <ul id="navbar">
            <li><a class="active" href="{% url 'shop:home' %}">Home</a></li>
            <li><a href="{% url 'shop:farmers' %}">About Farmers</a></li>
            <li><a href="{% url 'shop:about.us' %}">About Us</a></li>
            <li id="lg-bag"><a href="{% url 'cartapp:displaycart' %}"><i class="fa-solid fa-bag-shopping"></i></a></li>
            <a href="#" id="close"><i class="fa-solid fa-xmark"></i></a>

        </ul>

    </div>
    <div id="mobile">
        <a href="cart.html"><i class="fa-solid fa-bag-shopping"></i></a>
      <i id="bar" class="fa-solid fa-outdent"></i>

    </div>
</section>

<section id="page-header" class="about-header">
    <h2>#KnowUs</h2>
    <p>This or that, whatever befall, the farmer must feed them all!</p>


</section>
<section id="about-head" class="section-p1">
    <img src="{% static 'images/us.jpg' %}"  alt="us" >
    <div>
        <h2>Who We Are?</h2>
        <p>You must have heard the saying "This or that whatever we befall, the farmer must feed them all!" Countless superheros, hace been born on this earth,
        while many are fictional, a handful are real. Well we represent the real superheros- The Farmers

        Harvest Haven aims at unlocking access to safe-to-eat,pesticide screened fruits and vegetables directly sourced from our farmers.
        We are an online platform available to you on both website and mobile application.

        At Harvest Haven we are in the quest to create a positive movement- a movement aimed at reducing the gap between the consumer & a
            farmer, the movement that gives consumers to access to safe and non toxic farmers produce a movement that also uplifts the farmer community.

            Harvest Haven is agri tech start up bridging the gap between the fruits and vegetables supply chain. We connect the rural farmers to urban consumers.
        </p>

        <abbr title="">Harvest Haven</abbr>
        <br><br>
        <marquee bgcolor="#ccc" loop="-1" scrollamount="5" width="100%" direction="">Rural Farmers to Urban Consumers!</marquee>


    </div>
</section>
<section id="feature" class="section-p1">
    <div class="fe-box">
        <img src="{% static 'images/testing.jpg' %}" alt="Residue-Testing">
        <h6>Residue Testing</h6>
        <p>Regular pesticide residue
        testing</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/sourcing.jpg' %}" alt="Local-Sourcing">
        <h6>Local Sourcing</h6>
         <p>Sourcing locally from approved
         farmers</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/traceability.jpg' %}" alt="Traceability">
        <h6>Traceability</h6>
         <p>Supply chain traceability in
         farm travel</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/order.jpg' %}" alt="Order-Now">
        <h6>Order Now</h6>
         <p>Delivered Tomorrow</p>
    </div>


</section>










<section id="newsletter" class="section-p1 section-m1">
    <div class="newstext">
        <h4>Sign up for Newsletters</h4>
        <p>Get email updates about our latest <span>special offers</span></p>
    </div>
    <div class="form">
        <input type="text" placeholder="Your email address">
        <button class="normal">Sign up</button>
    </div>
</section>

<footer class="section-p1">
    <div class="col">
        <img class="logo" src="{% static 'images/logo.jpg' %}" alt="Logo">
        <h4>Contact</h4>
        <p><strong>Address:</strong> Harvest Haven Labs </p>
        <p><strong>Phone:</strong> 8921592755</p>
        <p><strong>Hours:</strong> 10.00 to 5.00, Mon - Sat</p>
        <div class="follow">
            <h4>Follow us</h4>
            <div class="icon">
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-pinterest"></i>
                <i class="fa-brands fa-youtube"></i>
            </div>
        </div>
    </div>

    <div class="col">
        <h4>About</h4>
        <a href="#">About us</a>
        <a href="#">Delivery Information</a>
        <a href="#">Privacy Policy</a>
        <a href="#">Terms & Conditions</a>
        <a href="#">Contact Us</a>
    </div>
    <div class="col">
        <h4>My Account</h4>
        <a href="#">Sign In</a>
        <a href="#">View Cart</a>
        <a href="#">My wishlist</a>
        <a href="#">Track my order</a>
        <a href="#">Help</a>
    </div>
    <div class="col install">
        <h4>Install App</h4>
        <p>From App Store or Google Play</p>
        <div class="row">
            <img src="{% static 'images/app.jpg' %}" alt="App">
            <img src="{% static 'images/play.jpg' %}" alt="Play">
        </div>
        <p>Secured Payment Gateways</p>
        <img src="{% static 'images/pay.jpg' %}" alt="Pay">
    </div>
    <div class="copyright">
        <p>Copyright @ 2024 Harvest Haven. All Rights Reserved.</p>
    </div>
</footer>
<script src="{% static 'script.js' %}"></script>
</body>
</html>

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HARVEST_HAVEN</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css\style.css' %}">
  </head>
  <body>
    {% include 'nav.html' %}
    {% block content %}

    {% endblock %}
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}



<div class="rw row mt-4 mb-5">
    <div class="col-lg-8 btn-light">
        <h5 class="fr">from saved Address</h5>
    {% for cartitem in cart %}
    <div class="rrw row border w-100 shadow">
        <div class="col-lg-2 col-md-3 col-sm-12">
            <img class="crtimg mt-2 shadow" src="{{cartitem.product.image.url}}" alt="">

            <h4 class="qt mt-4"><a href="{% url 'cartapp:removecart' cartitem.product.id %}"
                class="btn">-</a>{{cartitem.quantity}}<a href="{% url 'cartapp:addcart' cartitem.product.id %}" class="btn">+</a>
            </h4>
        </div>
        <div class="col-lg-7 border mt-2 mb-2">
            <h5 class="pro mt-3">{{cartitem.product}}</h5>
            <h6 class="des">{{cartitem.product.desc}}</h6>
            <h4 class="pr">${{cartitem.product.price}}</h4>
        </div>
        <div class="col-lg-3">
            <a href="{% url 'cartapp:fullremove' cartitem.product.id %}" class="cn btn btn-danger">Remove</a>
        </div>
    </div>
    {% endfor %}
    {% if cart %}
    <a href="{% url 'shop:home' %}" class="purch btn btn-primary mt-3 pt-2 pb-2">
        <h6>continue purchase</h6>
    </a>   
    </div>
    <div class="to col-lg-4 fixed-end border">
        <div class="pp row border">
            <h3>PRICE DETAILS</h3>
        </div>
        <div class="cc col-lg-12">
            <h4 class="ds mt-3">DISCOUNT<span class="dss mt-3">-$1020</span></h4>
            <h4 class="TOT mt-5">TOTAL AMOUNT<span class="tt">${{total}}</span></h4><hr>
            <h5 class="sav">you will save $1,020 on this order</h5>
        </div>
        <a href="{% url 'cartapp:placeorder' %}" class="plac btn btn-warning pt-2 mb-3"><h4>placeorder</h4></a>
        {% else %}
        <a href="{% url 'shop:home' %}"><h5 class="prpr">please purchase your product</h5></a>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="conta container-fluid mb-3 justify-content-center  d-flex ">
    <div class="card crd rounded-2  ms-4 w-50 me-4 mb-5 mt-3"style="border:0;">
        <div class="row">
            <h2 class="hed2">{{data.name}}</h2>
            <div class="cd card shadow-lg p-3 mb-5 p-3 mb-5 bg-body rounded mb-4">
                <img src="{{data.image.url}}" class="card-img-top rounded-2 ms-2 mt-3" alt="...">
                <div class="card-body">
                
      
                
                </div>
            </div>
            <div class="col2 col-5 ms-2">
                <h4>{{data.name}}</h4>
                <h5 class="" style="color: blue;">${{data.price}}</h5>
                <h5 class="ct mt-2" >category: {{data.category}}</h5>

                {% if data.stock >= 1 %}

                <!-- <button class="btn btn-primary me-3">Add to cart</button> -->
                <a href="{% url 'cartapp:addcart' data.id %}" type="button" class="btn btn-warning me-3">Add to cart</a>
                <button class="btn btn-danger me-3">Buy Now</button>
                {% else %}

                <span><h3 class="out" style="color: green;">out of stock</h3></div>
                {% endif %}
        </div>
    </div>
</div>
        
</div>

{% endblock %} 

templates/footer.html
 {% load static %}
<section id="newsletter" class="section-p1 section-m1">
    <div class="newstext">
        <h4>Sign up for Newsletters</h4>
        <p>Get email updates about our latest <span>special offers</span></p>
    </div>
    <div class="form">
        <input type="text" placeholder="Your email address">
        <button class="normal">Sign up</button>
    </div>
</section>

<footer class="section-p1">
    <div class="col">
        <img class="logo" src="{% static 'images/logo.jpg' %}" alt="Logo">
        <h4>Contact</h4>
        <p><strong>Address:</strong> Harvest Haven Labs </p>
        <p><strong>Phone:</strong> 8921592755</p>
        <p><strong>Hours:</strong> 10.00 to 5.00, Mon - Sat</p>
        <div class="follow">
            <h4>Follow us</h4>
            <div class="icon">
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-pinterest"></i>
                <i class="fa-brands fa-youtube"></i>
            </div>
        </div>
    </div>

    <div class="col">
        <h4>About</h4>
        <a href="#">About us</a>
        <a href="#">Delivery Information</a>
        <a href="#">Privacy Policy</a>
        <a href="#">Terms & Conditions</a>
        <a href="#">Contact Us</a>
    </div>
    <div class="col">
        <h4>My Account</h4>
        <a href="#">Sign In</a>
        <a href="#">View Cart</a>
        <a href="#">My wishlist</a>
        <a href="#">Track my order</a>
        <a href="#">Help</a>
    </div>
    <div class="col install">
        <h4>Install App</h4>
        <p>From App Store or Google Play</p>
        <div class="row">
            <img src="{% static 'images/app.jpg' %}" alt="App">
            <img src="{% static 'images/play.jpg' %}" alt="Play">
        </div>
        <p>Secured Payment Gateways</p>
        <img src="{% static 'images/pay.jpg' %}" alt="Pay">
    </div>
    <div class="copyright">
        <p>Copyright @ 2024 Harvest Haven. All Rights Reserved.</p>
    </div>
</footer>

<script src="{% static 'script.js' %}"></script>



</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if category %}

<div class="text-row">
        <h4>Trade-in-offer</h4>
        <h2>Super value deals</h2>
        <h1>On all products</h1>
        <p>Save more with coupons & up to 20% off!</p>
        <button>Shop Now</button>
    </div>
    <div class="image-row">
        <img src="{% static 'images/tomato.jpg' %}" alt="tomato">
    </div>

<div class="container-fluid mb-3">

 <h1 class="hed mt-5 mb-2">{{category.name}}</h1>
 <img class="can rounded-5 " src="{{category.image.url}}" style="margin-left: 600px;" width="30%" height="600" alt="">
 <h5 class="des mt-4 mb-3 pb-3 pt-3">{{category.desc}}</h5></div>
{% else %}
<section id="hero">
    <div class="text-row">
        <h4>Trade-in-offer</h4>
        <h2>Super value deals</h2>
        <h1>On all products</h1>
        <p>Save more with coupons & up to 20% off!</p>
        <button>Shop Now</button>
    </div>
    <div class="image-row">
        <img src="{% static 'images/tomato.jpg' %}" alt="tomato">
    </div>
</section>
<section id="feature" class="section-p1">
    <div class="fe-box">
        <img src="{% static 'images/testing.jpg' %}" alt="Residue-Testing">
        <h6>Residue Testing</h6>
        <p>Regular pesticide residue
        testing</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/sourcing.jpg' %}" alt="Local-Sourcing">
        <h6>Local Sourcing</h6>
         <p>Sourcing locally from approved
         farmers</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/traceability.jpg' %}" alt="Traceability">
        <h6>Traceability</h6>
         <p>Supply chain traceability in
         farm travel</p>
    </div>
     <div class="fe-box">
        <img src="{% static 'images/order.jpg' %}" alt="Order-Now">
        <h6>Order Now</h6>
         <p>Delivered Tomorrow</p>
    </div>


</section>
 <h2>Featured Products</h2>
 <p>The magic of Red in your Diet</p>

{% endif %}
<div class="container-fluid">
    <div class="card-group mb-3" >
      {% for i in products %}
        {% if i.available %}
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-3 mb-5 bg-body rounded mb-4 me-2 mr-5" style="padding-left: 200px;">
          <img src="{{i.image.url}}" height="125px" class="card-img-top rounded-4" alt="...">
          <div class="card-body" style="margin-left: 50px;">
            <h4 class="card-title">{{i.name}}</h4>
            <h6 class="card-text" style="color: blue;">${{i.price}}</h6>
            
          </div>
        </div>
        </a>

      
        {% endif %}
        {% endfor %}
    </div>
  </div>
<section id="sm-banner" class="section-p1">
    <div class="banner-box">
        <h2>Fresh Vegetables</h2>
        <button class="white"> Shop Now</button>

    </div>
     <div class="banner-box banner-box2">
        <h2>Know your Farmer</h2>
        <button class="white">Know More</button>

    </div>
</section>

<section id="banner3">
    <div class="banner-box">
        <h6>Control Blood Pressure, the right way!</h6>
        <button class="white">Show More</button>

    </div>
    <div class="banner-box2">
        <h6>Five reasons why brocoli should be a part of our diet!</h6>
        <button class="white">Show More</button>

    </div>
    <div class="banner-box3">
        <h6>Five tips that you prevent cough!</h6>
        <button class="white">Show More</button>

    </div>
</div>

</section>

<div class="paginator mx-auto">

  {% if products.paginator.num_pages > 1 %}<hr>
    <div class="text-center">
      {% for pg in products.paginator.page_range %}
      <a href="?page={{pg}}" class="btn btn-dark btn-sm {% if products.number == pg %}active{% endif %}">{{pg}}</a>
      {% endfor %}
    </div>
  {% endif %}

</div>


{% endblock %}

templates/loginuser.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 rounded-3 bg-light  login_page">
    <form action="" method="post" class="mx-auto" style="width: 30%;">
        {% csrf_token %}
        <h3 class="login text-center pt-3">LogIn</h3>
        <div class="form-group login_input  pt-4 ">
            <input type="text" class="form-control" placeholder="Username" name="username">
        </div>
        <div class="form-group  login_input pt-1 ">
            <input type="password" class="form-control" placeholder="Password" name="password">
        </div>
        <div class="form-group  login_input  pt-2 ">
            <button type="submit" class="btn btn-primary" style="margin-left: 160px;">Login</button>
        </div>
    </form>
</div>

</div>
</div>
</div>
</div>

{% endblock %}

templates/nav.html
{% load static %}

<section id="header">
    <a href="#"><img src="{% static 'images/icon.jpg' %}" width="280px" height="100px" class="logo" alt="image1" ></a>
    <div>
        <ul id="navbar">
            <form class="d-flex" role="search" action="{% url 'searchapp:searchproduct' %}" method="GET">
        <input class="form-control me-2 mt-3 mb-3" type="search"  name="q" placeholder="Search" aria-label="Search">

            <li><a class="active" href="{% url 'shop:home' %}">Home</a></li>
            <li><a href="{% url 'shop:farmers' %}">About Farmers</a></li>
            <li><a href="{% url 'shop:about.us' %}">About Us</a></li>


            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            𝗘𝗫𝗣𝗟𝗢𝗥𝗘
           </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:home' %}">ALL products</a></li>
            {% for link in links %}
            <li><a class="dropdown-item" href="{{link.get_url}}">{{link.name}}</a></li>

            {% endfor %}

        </ul>
        </ul>

      </div>
    </div>
    <div id="mobile">
        <a href="cart.html"><i class="fa-solid fa-bag-shopping"></i></a>
      <i id="bar" class="fa-solid fa-outdent"></i>

    </div>
</section>

<form>
        <a class="pt-4" href="{% url 'cartapp:displaycart' %}"><svg xmlns="http://www.w3.org/2000/svg" height="38" viewBox="0 -960 960 960" width="40"><path fill="black" d="M280-80q-33 0-56.5-23.5T200-160q0-33 23.5-56.5T280-240q33 0 56.5 23.5T360-160q0 33-23.5 56.5T280-80Zm400 0q-33 0-56.5-23.5T600-160q0-33 23.5-56.5T680-240q33 0 56.5 23.5T760-160q0 33-23.5 56.5T680-80ZM246-720l96 200h280l110-200H246Zm-38-80h590q23 0 35 20.5t1 41.5L692-482q-11 20-29.5 31T622-440H324l-44 80h480v80H280q-45 0-68-39.5t-2-78.5l54-98-144-304H40v-80h130l38 80Zm134 280h280-280Z"/></svg></a>

        {% if user.is_authenticated %}

        <span class="text-light">{{user}}</span>
        <a href="{% url 'auth:logout' %}" class="btn btn-outline-danger " type="button">Logout</a>
        {% else %}
        <a href="{% url 'auth:login' %}"  class="btn btn-outline-success me-2" type="button">Login</a>
        <a href="{% url 'auth:register' %}" class="btn btn-outline-primary me-2" type="button">Signup</a>
</form>
        {% endif %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="card-group mb-3">
      
      {% for i in products %}
      
        <a href="{% url 'shop:details' i.id %}">
        <div class="cad border p-3 mb-5 bg-body rounded mb-4 me-2 mr-5">
          <img src="{{i.image.url}}" height="400px" width="1000px" class="card-img-top rounded-4 " alt="...">
          <div class="card-body">
            <h3 class="card-title">{{i.name}}</h3>
            <h5 class="card-text">${{i.price}}</h5>
            <h6 class="card-text">{{i.category}}</h6>
          </div>
        </div>
        </a>
       
        {% endfor %}

      </div>
</div>
{% endblock %}